/**
 * CityPay POS API
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API is available from https://github.com/citypay/citypay-pos-api  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PrintRequest model module.
* @module model/PrintRequest
* @version 1.0.0
*/
export default class PrintRequest {
    /**
    * Constructs a new <code>PrintRequest</code>.
    * @alias module:model/PrintRequest
    * @class
    * @param identifier {String} Must include an identifier for a transaction that has been carried out on the device
    */

    constructor(identifier) {
        

        
        

        this['identifier'] = identifier;

        
    }

    /**
    * Constructs a <code>PrintRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PrintRequest} obj Optional instance to populate.
    * @return {module:model/PrintRequest} The populated <code>PrintRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrintRequest();

            
            
            

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Must include an identifier for a transaction that has been carried out on the device
    * @member {String} identifier
    */
    identifier = undefined;
    /**
    * The instruction prints the cardholder copy of the receipt by default. If you want to reprint the merchant copy, append “type”:”merchant” to the body of the request.
    * @member {String} type
    */
    type = undefined;








}


