/**
 * CityPay POS API
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API is available from https://github.com/citypay/citypay-pos-api  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SaleResponse model module.
* @module model/SaleResponse
* @version 1.0.0
*/
export default class SaleResponse {
    /**
    * Constructs a new <code>SaleResponse</code>.
    * @alias module:model/SaleResponse
    * @class
    * @param success {Boolean} Defines whether the sale was successfully created
    * @param identifier {String} The identifier presented to the sale request
    */

    constructor(success, identifier) {
        

        
        

        this['success'] = success;this['identifier'] = identifier;

        
    }

    /**
    * Constructs a <code>SaleResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SaleResponse} obj Optional instance to populate.
    * @return {module:model/SaleResponse} The populated <code>SaleResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SaleResponse();

            
            
            

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * Defines whether the sale was successfully created
    * @member {Boolean} success
    */
    success = undefined;
    /**
    * The identifier presented to the sale request
    * @member {String} identifier
    */
    identifier = undefined;
    /**
    * Description should the sale request not be accepted
    * @member {String} description
    */
    description = undefined;








}


