/**
 * CityPay POS API
 * CityPay Point of Sale API for payment with card present devices including EMV readers and contactless POS readers.  The API makes it simple to add EMV and contactless card acceptance to iOS, Android, Tablet and desktop applicaitons using a HTTPS protocol. It segregates the complexity of payment processing from the sales environment and eliminates any necessity for the target system to handle card data. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@citypay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TransactionData from './TransactionData';





/**
* The TransactionResult model module.
* @module model/TransactionResult
* @version 1.0.0
*/
export default class TransactionResult {
    /**
    * Constructs a new <code>TransactionResult</code>.
    * @alias module:model/TransactionResult
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TransactionResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TransactionResult} obj Optional instance to populate.
    * @return {module:model/TransactionResult} The populated <code>TransactionResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionResult();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('is_complete')) {
                obj['is_complete'] = ApiClient.convertToType(data['is_complete'], 'Boolean');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = TransactionData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
    * A description of the status of a transaction
    * @member {String} status
    */
    status = undefined;
    /**
    * The indentifier uniquely identifying the transaction
    * @member {String} identifier
    */
    identifier = undefined;
    /**
    * A boolean value stating whether the transaction has completed. The value will be false if the transaction is in progress. Should the value be true, a property containing the transaction details is made available.
    * @member {Boolean} is_complete
    */
    is_complete = undefined;
    /**
    * @member {module:model/TransactionData} data
    */
    data = undefined;








}


